version: '3.5'

services:
  web:
    image: nginx
    ports:
      - 80:80
    container_name: 'web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:/mnt/data01/web/web/dist
